# Generated by Django 3.0.6 on 2020-05-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_desc',
            new_name='blog_contents',
        ),
    ]
