# Generated by Django 3.0.6 on 2020-05-19 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200519_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 3, 55, 997032), verbose_name='Date Published'),
        ),
    ]
