# Generated by Django 3.0.6 on 2020-05-20 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200519_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 11, 0, 3, 187493), verbose_name='Date Published'),
        ),
    ]
