# Generated by Django 3.0.6 on 2020-05-20 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200520_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 22, 16, 6, 569823), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.blogSeries', verbose_name='Series'),
        ),
    ]
