# Generated by Django 3.0.6 on 2020-05-20 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200520_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 22, 18, 51, 243691), verbose_name='Date Published'),
        ),
    ]
