# Generated by Django 3.0.6 on 2020-05-20 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200520_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 22, 22, 1, 898510), verbose_name='Date Published'),
        ),
    ]
