# Generated by Django 3.0.6 on 2020-05-21 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200520_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 16, 48, 34, 824890), verbose_name='Date Published'),
        ),
    ]
