# Generated by Django 3.0.6 on 2020-05-25 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200521_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_publishedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 22, 34, 56, 539579), verbose_name='Date Published'),
        ),
    ]
